#!/bin/bash

# Pieces
headers='headers.tex'
closers='closers.tex'
output='paper.tex'

pieces='intro.tex skew-normal.tex method-of-moments.tex accuracy.tex resources.tex'
appendices='figures.tex calc-sn-demo.tex'
bib='bibliography.bib'


# Build document
cat $headers                > $output
echo                       >> $output

for file in $pieces; do
  cat $file                >> $output
  echo                     >> $output
done

echo \\appendix            >> $output
cat $appendices            >> $output
echo                       >> $output

cat $closers               >> $output


# Compile document
pdflatex $output; echo; echo;
bibtex $(echo $output | sed 's/.tex//'); echo; echo;
pdflatex $output; echo; echo;
pdflatex $output
