#!/bin/bash

input="$(basename $(pwd)).tex"
biburl="$HOME/projects/capstone/pieces/bibliography/bibliography.bib"

echo \\documentclass\{article\}                      > output.tex
echo \\usepackage\{jcapstone\}                      >> output.tex
echo \\begin\{document\}                            >> output.tex
echo                                                >> output.tex
cat $input                                          >> output.tex
echo                                                >> output.tex

if [ -f appendix.tex ]; then
  echo \\appendix                                   >> output.tex
  cat appendix.tex                                  >> output.tex
  echo                                              >> output.tex
fi

echo \\bibliography\{$biburl\}                      >> output.tex
echo \\bibliographystyle\{plainnat\}                >> output.tex
echo \\end\{document\}                              >> output.tex

latex output.tex
echo
echo
bibtex output
echo
echo
latex output.tex
echo
echo
pdflatex output.tex
