#!/bin/bash

input='method-of-moments.tex'
output='output.tex'

echo \\documentclass\{article\}  > $output
echo \\usepackage\{joyce-math\} >> $output
echo \\begin\{document\}        >> $output
echo                            >> $output
cat $input                      >> $output
echo                            >> $output
echo \\end\{document\}          >> $output

pdflatex $output
