#!/bin/bash

headers='headers.tex'
closers='closers.tex'
files='intro.tex skew-normal.tex method-of-moments.tex accuracy.tex resources.tex'

output='presentation.tex'

cat $headers  > $output
echo         >> $output
for file in $files; do
  cat $file  >> $output
  echo       >> $output
done
cat $closers >> $output

# Compile document
pdflatex $output
#pdflatex $output; echo; echo;
#bibtex $(echo $output | sed 's/.tex//'); echo; echo;
#pdflatex $output; echo; echo;
#pdflatex $output
