#!/bin/bash

# Pieces
root="$HOME/projects/capstone/pieces"
biburl="$root/bibliography/bibliography.bib"

intro="$root/final-paper/intro.tex"
properties="$root/properties/properties.tex"
moments="$root/method-of-moments/method-of-moments.tex"
mabs="$root/mabs/mabs.tex"
conclusion="$root/final-paper/conclusion.tex"


# Build document
echo \\documentclass\{article\}                      > output.tex
echo \\usepackage\{jcapstone\}                      >> output.tex
echo \\begin\{document\}                            >> output.tex
echo                                                >> output.tex

for file in $intro $properties $moments $mabs $conclusion; do
  cat $file >> output.tex
  echo      >> output.tex
done

echo \\bibliography\{$biburl\}                      >> output.tex
echo \\bibliographystyle\{plainnat\}                >> output.tex
echo \\end\{document\}                              >> output.tex


# Compile document
pdflatex output.tex
echo
echo
bibtex output
echo
echo
pdflatex output.tex
echo
echo
pdflatex output.tex
