#!/bin/bash

compfile='comparison.js'
cat comparison-headers.js > $compfile
for file in comparison-*.json; do
  cat $file >> $compfile
done

mabsfile='mabs.js'
cat mabs-headers.js > $mabsfile
for file in mabs-*.json; do
  cat $file >> $mabsfile
done
